wpsblog/wpsblog/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Post(models.Model):
    title = models.CharField(
        max_length=120,
    )
    content = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "posts:detail",
            kwargs={
                "post_id": self.id,
            }
        )

    def get_update_url(self):
        return reverse(
            "posts:update",
            kwargs={
                "post_id": self.id,
            }
        )


class NaverPost(models.Model):
    keyword = models.CharField(
        max_length=16,
    )

    title = models.CharField(
        max_length=256,
    )
    content = models.TextField()
    thumbnail_image_url = models.URLField()
    original_url = models.URLField()

    def __str__(self):
        return self.title

wpsblog/wpsblog/models/__init__.py
from .post import Post
from .naver_post import NaverPost
from .comment import Comment

wpsblog/wpsblog/models/comment.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User


class Comment(models.Model):
    user = models.ForeignKey(User)
    post = models.ForeignKey("Post")

    content = models.TextField()

    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return reverse(
            "posts:detail",
            kwargs={
                "pk": self.post.id,
            },
        ) + "#comment-" + str(self.id)

wpsblog/wpsblog/models/naver_post.py
from django.db import models


class NaverPost(models.Model):
    keyword = models.CharField(
        max_length=16,
    )

    title = models.CharField(
        max_length=256,
    )
    content = models.TextField()
    thumbnail_image_url = models.URLField()
    original_url = models.URLField()

    def __str__(self):
        return self.title

wpsblog/wpsblog/models/post.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User


class PostManager(models.Manager):

    def public(self):
        return self.filter(is_public=True)


class Post(models.Model):

    objects = PostManager()

    user = models.ForeignKey(User)

    title = models.CharField(
        max_length=120,
    )
    content = models.TextField()
    image = models.ImageField(
        blank=True,
        null=True,
    )
    is_public = models.BooleanField(
        default=True,
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "posts:detail",
            kwargs={
                "pk": self.id,
            }
        )

    def get_update_url(self):
        return reverse(
            "posts:update",
            kwargs={
                "post_id": self.id,
            }
        )

    def get_image_url(self):
        if self.image:
            return self.image.url
        return "http://placehold.it/300x200"

wpsblog/wpsblog/settings/__init__.py
from .production import *

wpsblog/wpsblog/settings/partials/__init__.py
from .auth import *
from .base import *
from .static import *
from .database import *
from .internationalization import *

wpsblog/wpsblog/settings/partials/auth.py
# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Custom Authentication URLs
LOGIN_URL = "/login/"

wpsblog/wpsblog/urls/__init__.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from wpsblog.views import *


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^about/us/$', about, name="about"),
    url(r'^pricing/$', PricingView.as_view(), name="pricing"),
    url(r'^rooms/(?P<room_id>\d+)/$', room, name="room"),
    url(r'^news/$', news, name="news"),

    url(r'^policy/', include("wpsblog.urls.policy", namespace="policy")),
    url(r'^posts/', include("wpsblog.urls.posts", namespace="posts")),
    url(r'^', include("wpsblog.urls.auth", namespace="auth")),
    url(r'^bitly/', include("wpsblog.urls.bitly", namespace="bitly")),


    url(r'^naver/posts/$', naver_posts_list, name="naver-posts-list"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wpsblog/wpsblog/urls/auth.py
from django.conf.urls import url

from wpsblog.views.auth import *


urlpatterns = [
    url(r'^signup/$', SignupView.as_view(), name="signup"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^my/page/$', MypageView.as_view(), name="mypage"),
]

wpsblog/wpsblog/views/__init__.py
from .home import HomeView
from .about import about
from .pricing import PricingView
from .room import room
from .news import news
from .policy import terms, privacy, disclaimer
from .posts import *
from .naver_posts import naver_posts_list
from .posts import *
from .auth import *

wpsblog/wpsblog/views/about.py
from django.shortcuts import render


def about(request):
    return render(
        request,
        "about.html",
        {},
    )

wpsblog/wpsblog/views/home.py
from django.shortcuts import render
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)

        context["site_name"] = "wps blog"
        return context

wpsblog/wpsblog/views/naver_posts.py
from django.shortcuts import render

from wpsblog.models import NaverPost


def naver_posts_list(request):
    keyword = request.GET.get("keyword")
    query = request.GET.get("query")
    naver_posts = NaverPost.objects.all()

    if keyword:
        naver_posts = naver_posts.filter(keyword=keyword)

    if query:
        naver_posts = naver_posts.filter(title_contains=query)

    return render(
        request,
        "naver_posts/list.html",
        {
            "keyword": keyword,
            "query": query,
            "naver_posts": naver_posts,
        },
    )

wpsblog/wpsblog/views/news.py
import json
import requests

from django.shortcuts import render


def news(request):
    search = request.GET.get("search")
    response = requests.get("https://watcha.net/home/news.json?page=1&per=50")
    news_dict = json.loads(response.text)
    news_list = news_dict.get("news")
    if search:
        news_list = list(filter(
            lambda news: search in news.get('title'),
            news_list,
        ))
    return render(
         request,
         "news.html",
         {"news_list": news_list},
    )

wpsblog/wpsblog/views/policy.py
from django.shortcuts import render


def terms(request):
    return render(
        request,
        "policy/terms.html",
        {},
    )


def privacy(request):
    return render(
        request,
        "policy/privacy.html",
        {},
    )


def disclaimer(request):
    return render(
        request,
        "policy/disclaimer.html",
        {},
    )

wpsblog/wpsblog/views/posts/__init__.py
from .list import PostListView
from .detail import PostDetailView
from .new import new
from .create import PostCreateView
from .edit import edit
from .update import update
from .delete import delete
from .comments import *

wpsblog/wpsblog/views/pricing.py
from django.views.generic import View
from django.http.response import HttpResponse


class PricingView(View):

    def get(self, request, *args, **kwargs):
        return HttpResponse("Pricing Table")

wpsblog/wpsblog/views/room.py
import requests

from django.http.response import HttpResponse


def room(request, room_id):
    url = "http://api.zigbang.com/v1/items?detail=true&item_ids=" + room_id
    response = requests.get(url)
    return HttpResponse(
        response.content,
        content_type="application/json",
    )

wpsblog/wpsblog/templates/posts/comments_edit.html
{% extends "base.html" %}


{% block content %}
<h1>{{ post.title }}</h1>
<p>{{ post.content }}</p>

<ul>
  <li><a href="{% url "posts:edit" post_id=post.id %}">Edit</a></li>
  <li><a href="{% url "posts:delete" post_id=post.id %}">Delete</a></li>
</ul>


<h2>Comments ( {{ post.comment_set.count }} )</h2>
<ul>
  {% for post_comment in post.comment_set.all %}
    {% if comment == post_comment %}
      <li>
        <form action="{% url "posts:comments-update" post_id=post.id comment_id=comment.id %}" method="POST">
          {% csrf_token %}
          <input type="text" name="content" value="{{ comment.content }}">
          <input type="submit" value="수정">
        </form>
      </li>
    {% else %}
      <li id="comment-{{ post_comment.id }}">{{ post_comment.content }}</li>
    {% endif %}
  {% endfor %}
</ul>


<h2>New Comment</h2>
<form action="/posts/{{ post.id }}/comments/create/" method="POST">
  {% csrf_token %}
  <input type="text" name="content" placeholder="댓글">
  <input type="submit" value="댓글 달기">
</form>

{% endblock %}

wpsblog/wpsblog/templates/posts/detail.html
{% extends "base.html" %}


{% block content %}
<h1>{{ post.title }}</h1>
<p>{{ post.content }}</p>

<ul>
  <li><a href="{% url "posts:edit" post_id=post.id %}">Edit</a></li>
  <li><a href="{% url "posts:delete" post_id=post.id %}">Delete</a></li>
</ul>


<h2>Comments ( {{ post.comment_set.count }} )</h2>
<ul>
  {% for comment in post.comment_set.all %}
  <li id="comment-{{ comment.id }}">
    {{ comment.user.username }}
    {{ comment.content }}
    <a href="{% url "posts:comments-edit" post_id=post.id comment_id=comment.id %}">Edit</a>
    <a href="{% url "posts:comments-delete" post_id=post.id comment_id=comment.id %}">Delete</a>
  </li>
  {% endfor %}
</ul>


<h2>New Comment</h2>
<form action="/posts/{{ post.id }}/comments/create/" method="POST">
  {% csrf_token %}
  <input type="text" name="content" placeholder="댓글">
  <input type="submit" value="댓글 달기">
</form>

{% endblock%}

wpsblog/wpsblog/templates/posts/edit.html
{% extends "base.html" %}


{% block content %}
  <h1>Edit Post</h1>
  {% include "posts/form.html" with action=post.get_update_url %}
{% endblock %}

wpsblog/wpsblog/templates/posts/form.html
<form action="{{ action }}" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="title" placeholder="제목" value="{% if post %}{{ post.title }}{% endif %}">
  <input type="text" name="content" placeholder="본문" value="{% if post %}{{ post.content }}{% endif %}">
  <input type="file" name="image">
  <input type="submit" value="publish">
</form>

wpsblog/wpsblog/templates/posts/list.html
{% extends "base.html" %}


{% block content %}
<h1>Posts List ( {{ posts | length }} )</h1>

<ul>
  {% for post in posts %}
    <li>
	  <img src="{{ post.get_image_url }}" alt="{{ post.title }}">
      <a href="{% url "posts:detail" pk=post.id %}">
        <h2>{{ post.title }}<span>({{ post.comment_set.count }})</span></h2>
      </a>
      <p>{{ post.content }}</p>
	</li>
  {% endfor %}
</ul>
{% endblock %}

wpsblog/wpsblog/templates/posts/new.html
{% extends "base.html" %}


{% block content %}
  <h1>New Post</h1>
  {% include "posts/form.html" with action="/posts/create/" %}
{% endblock %}